const Types = {
  TEST: 'TEST',
  SAVE_USER: 'USER/SAVE',
  SAVE_USER_TYPE: 'USER/SAVE-TYPE',
  SAVE_LIST_JOBS: 'RECRUITMENT/SAVE_LIST_JOBS',
  SAVE_LIST_FILTERS: 'RECRUITMENT/SAVE_LIST_FILTERS',
};

export default Types;
