const Types = {
  TEST: 'TEST',
  SAVE_USER: 'USER/SAVE',
  SAVE_USER_TYPE: 'USER/SAVE-TYPE',
  SAVE_LIST_JOBS: 'RECRUITMENT/SAVE_LIST_JOBS',
  SAVE_LIST_FILTERS: 'RECRUITMENT/SAVE_LIST_FILTERS',
  SAVE_LIST_STATUS_APPLIED: 'RECRUITMENT/SAVE_LIST_STATUS_APPLIED',
  SAVE_CURRENT_LOCATION: 'USER/SAVE_CURRENT_LOCATION',
  SAVE_APP_LOCATION: 'USER/SAVE_APP_LOCATION',
  SAVE_DETAIL_RECUITMENT: 'USER/SAVE_DETAIL_RECUITMENT',
};

export default Types;
